FROM oracle/graalvm-ce:20.2.0-java11 as graalvm
RUN gu install native-image

COPY . /home/app/micronaut-udemy-kafka
WORKDIR /home/app/micronaut-udemy-kafka

RUN native-image --no-server -cp build/libs/micronaut-*-all.jar

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
# No rest api, so no port expose
# EXPOSE 8080
COPY --from=graalvm /home/app/micronaut-udemy-kafka/micronaut-udemy-kafka /app/micronaut-udemy-kafka
ENTRYPOINT ["/app/micronaut-udemy-kafka"]


